name: Clang Diff Format Check

on:
  pull_request:
    branches:
      - develop
jobs:
  ClangFormat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch git
        run: git fetch
      - name: Run Clang-Format-Diff.py
<<<<<<< HEAD
        run: git diff -U0 origin/develop -- . ':(exclude)src/qt/dashstrings.cpp' ':(exclude)src/qt/locale/' | ./contrib/devtools/clang-format-diff.py -p1
=======
        run: git diff -U0 origin/develop -- . ':(exclude)src/qt/hootstrings.cpp' ':(exclude)src/qt/locale/' | ./contrib/devtools/clang-format-diff.py -p1
>>>>>>> temporal

